sections:
  main:
    display: Main
    fields:
      title:
        display: Title
        type: text
        localizable: true
      content:
        cheatsheet: false
        restrict_assets: false
        type: markdown
        instructions: 'A few lines shown under the title'
        display: Introduction
      sections:
        sets:
          section:
            display: Section
            fields:
              section_title:
                type: text
                display: Title
              section_decoration:
                options:
                  none: None
                  highlight: Highlighted
                inline: true
                type: radio
                display: Decoration
                default: none
              modules:
                sets:
                  prose:
                    display: Prose
                    fields:
                      prose_content:
                        cheatsheet: false
                        restrict_assets: false
                        type: markdown
                        display: prose_content
                      prose_figure_images:
                        container: main
                        folder: /
                        restrict: false
                        type: assets
                        display: 'Figure image(s)'
                      prose_figure_caption:
                        type: text
                        display: 'Figure Caption'
                      prose_figure_style:
                        options:
                          figure--bleed-start: 'Bleed left'
                          figure--bleed-end: 'Bleed right'
                          figure--stage: Stage
                          figure--full: 'Force full width'
                          figure--gallery: 'Gallery mode'
                        type: checkboxes
                        display: 'Figure Style'
                      prose_figure_color:
                        options:
                          default: None
                          figure--green: Green
                          figure--blue: Blue
                          figure--red: Red
                          figure--yellow: Yellow
                          figure--purple: Purple
                        inline: true
                        type: radio
                        display: 'Figure colour'
                        default: default
                      prose_figure_align:
                        options:
                          top: Top
                          bottom: Bottom
                        inline: true
                        type: radio
                        display: 'Align Figure'
                        default: top
                  quote:
                    display: Quote
                    fields:
                      quote_content:
                        type: textarea
                        display: Content
                      quote_cite:
                        type: text
                        display: Citation
                  figure:
                    display: Figure
                    fields:
                      figure_images:
                        container: main
                        folder: /
                        restrict: false
                        type: assets
                        display: Image(s)
                      figure_caption:
                        type: markdown
                        display: 'Figure Caption'
                      figure_style:
                        options:
                          figure--bleed-start: 'Bleed left'
                          figure--bleed-end: 'Bleed right'
                          figure--stage: Stage
                          figure--full: 'Force full width'
                          figure--gallery: 'Gallery mode'
                        type: checkboxes
                        display: 'Figure Style'
                      figure_color:
                        options:
                          default: None
                          figure--green: Green
                          figure--blue: Blue
                          figure--red: Red
                          figure--yellow: Yellow
                          figure--purple: Purple
                        inline: true
                        type: radio
                        display: 'Figure colour'
                        default: default
                  outcomes:
                    display: Outcomes
                    fields:
                      outcomes:
                        sets:
                          outcome:
                            display: outcome
                            fields:
                              outcome_title:
                                type: text
                                display: Title
                              outcome_content:
                                cheatsheet: false
                                restrict_assets: false
                                type: markdown
                                display: Content
                        type: replicator
                        display: Outcome
                  hero:
                    display: Hero
                    fields:
                      hero_image:
                        container: main
                        folder: /
                        restrict: false
                        type: assets
                        display: Image(s)
                      hero_caption:
                        cheatsheet: false
                        restrict_assets: false
                        type: markdown
                        display: Caption
                type: replicator
                display: Modules
        type: replicator
        display: Sections
  sidebar:
    display: Sidebar
    fields:
      meta:
        sets:
          meta_set:
            display: 'Meta set'
            fields:
              meta_title:
                type: text
                display: Title
              meta_value:
                type: text
                display: Value
        type: replicator
        display: Meta
      cover:
        type: assets
        container: main
        folder: 
        restrict: false
        display: 'Cover Image'
        max_files: 1
      noun:
        type: text
        display: Noun
        instructions: 'A single (proper-)noun that describes this page/post'
taxonomies: false
title: Default
create_title: 'Create a page or post'
