sections:
  main:
    display: Main
    fields:
      title:
        display: Title
        type: text
      content:
        cheatsheet: false
        restrict_assets: false
        type: markdown
        display: subheading
      services:
        sets:
          card:
            display: Card
            fields:
              card_title:
                type: text
                display: Title
              card_cover:
                container: main
                folder: /
                restrict: false
                max_files: 1
                type: assets
                display: Cover
              card_content:
                cheatsheet: false
                restrict_assets: false
                type: markdown
                display: Contents
              card_footer:
                type: markdown
                display: Footer
        type: replicator
        display: Services
taxonomies: true
title: Services
create_title: 'Create a new services page'
